version: "3.9"

services:
  rag-api:
    build: .
    container_name: rag_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/rag-fundamentals-471014.json
    restart: unless-stopped
